FROM ubuntu:noble

RUN apt update && apt install -y git sudo

RUN git clone https://github.com/RoboCup-SSL/ssl-vision.git

WORKDIR /ssl-vision

RUN bash InstallPackagesUbuntu.sh

RUN make

RUN rm -rf /var/lib/apt/lists/*