#!/bin/bash

# Nome da sessão
SESSION_NAME="meus_paines"

# Inicia uma nova sessão tmux
tmux new-session -d -s $SESSION_NAME

# Cria os painéis
tmux split-window -v               
tmux split-window -h
tmux split-windows -h
tmux split-window -h -t 1          
tmux split-window -h -t 0        
tmux split-window -h -t 1
tmux split-window -h -t 0
tmux split-window -h -t 6

# Envia comandos para os painéis
tmux send-keys -t $SESSION_NAME:0.0 'cd endereco_do_gui' C-m #Coloque o endereço do gui aqui
tmux send-keys -t $SESSION_NAME:0.0 'npm run dev' C-m
tmux send-keys -t $SESSION_NAME:0.1 'ros2 run vision visionNode' C-m
tmux send-keys -t $SESSION_NAME:0.2 'ros2 run referee referee_node' C-m
tmux send-keys -t $SESSION_NAME:0.3 'ros2 run control_unit mainNode' C-m
tmux send-keys -t $SESSION_NAME:0.4 'ros2 topic echo /TeamCommand' C-m
tmux send-keys -t $SESSION_NAME:0.5 'ros2 topic echo /Refereetopic' C-m
tmux send-keys -t $SESSION_NAME:0.6 'ros2 topic echo /Visiontopic' C-m

# Anexa à sessão para visualizar os resultados
tmux attach-session -t $SESSION_NAME
